### ISSUE TITLE
compliance tests are failing 

### ISSUE THREAD

**Issue by HemangChothani** [cloudspannerecosystem/python-spanner-sqlalchemy#25]
Compliance tests are not running with new version of `sqlalchemy`
## Expected Behavior
Successfully run the tests

## Actual Behavior
Throw as error `sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'None'`

## Steps to Reproduce the Problem

1. nox -s compliance_test

## Specifications

- Version: sqlalchemy== 1.4.0

**Comment by IlyaFaer** [comment]
I've checked tests locally with SQLAlchemy 1.4, everything is working fine. Most likely, the problem is in argument you've passed into `create_engine()`. See the repo readme for an example of how to connect to the database.
