### ISSUE TITLE
Add unit tests for opentelemtry tracing

### ISSUE THREAD

**Issue by HemangChothani** [cloudspannerecosystem/python-spanner-sqlalchemy#76]
Reference from the comment on PR https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/pull/51#pullrequestreview-667477420

**Comment by IlyaFaer** [comment]
This issue seems to be fixed by the PR https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/pull/88
Closing
