### ISSUE TITLE
String-type columns with undefined length break during load but not creation

### ISSUE THREAD

**Issue by aderk** [cloudspannerecosystem/python-spanner-sqlalchemy#86]
## Expected Behavior
a STRING(MAX) column is loadable

## Actual Behavior
STRING(MAX) column loading raises exception:
```
google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py", line 445, in get_columns
    size = int(col[1][7:end])
ValueError: invalid literal for int() with base 10: 'MAX'
```

STRING(MAX) is an alias for STRING(2621440) https://cloud.google.com/spanner/docs/data-definition-language#string

## Steps to Reproduce the Problem
```python
from sqlalchemy import Column, Integer, MetaData, Text, Table, create_engine

project_id = 'foo'
instance_id = 'bar'
database = 'baz'

spanner_uri = f'spanner:///projects/{project_id}/instances/{instance_id}/databases/{database}'

# Create a table with one `Text`-type column
engine = create_engine(spanner_uri)
metadata = MetaData(bind=engine)
t = Table("TestTable", metadata, Column("TestColumn", Text, nullable=False))
metadata.create_all(engine)
print('Done creating table')

# Load it again
t2 = Table("TestTable", MetaData(bind=create_engine(spanner_uri)), autoload=True)
```

## Specifications

- Version: c7e66fdaea55df8ff7bcaec1984813bd3bed20b0
- Platform: linux

**Comment by IlyaFaer** [comment]
@aderk, thank you for the working snippet!

Yeah, I see the problem. @larkee, I assume the same is actual for `BYTES` type. Will deal with it.

**Comment by aderk** [comment]
Sorry I just saw this. I updated `BYTES` as well. I'll defer the PR to you, @IlyaFaer, unless you advise me otherwise. Cheers

**Comment by IlyaFaer** [comment]
> I'll defer the PR to you, @IlyaFaer, unless you advise me otherwise

No problem 👌
