### ISSUE TITLE
Using __table_args__ to specify an interleaved child ignores cascade action

### ISSUE THREAD

**Issue by geudrik** [cloudspannerecosystem/python-spanner-sqlalchemy#98]
## Expected Behavior
`INTERLEAVE IN PARENT ob_malware ON DELETE CASCADE;`

## Actual Behavior
`INTERLEAVE IN PARENT ob_malware ON DELETE NO ACTION;`

## Steps to Reproduce the Problem
Create a table using a declarative base, and specify 
```
__table_args__ = {
        "spanner_interleave_in": "ob_malware",
        "spanner_interleave_on_delete_cascade": True
    }
```
The table is configured correctly to be interleaved, but cascade is set to `NO ACTION`

## Specifications

- Version: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/tree/v0.1.0
- Platform: Python 3.9

**Comment by larkee** [comment]
Thank you for filing this issue!

I was able to replicate the problem and discovered that the implementation was not checking the passed bool due to a typo in the keyword :sweat_smile: 

I have created a fix PR here: #99

**Comment by geudrik** [comment]
Thanks for a quick fix! 😀

**Comment by geudrik** [comment]
Any idea when this will make it onto pypi? We're ready to start building with it
